# Generated by Django 5.2.4 on 2025-08-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_mensajecontacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen_perfil',
            field=models.ImageField(default='assets/img/avatars/default_3.png', upload_to='imagenes_perfiles/'),
        ),
    ]
