# Generated by Django 5.2.4 on 2025-08-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_perfil_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_perfiles/'),
        ),
    ]
