# Generated by Django 5.2.4 on 2025-08-15 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_remove_post_categoria_post_categorias_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categorias',
            new_name='categoria',
        ),
    ]
