# Generated by Django 5.2.4 on 2025-08-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_rename_categorias_post_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Marcar si es una noticia destacada principal'),
        ),
    ]
