# Generated by Django 5.2.4 on 2025-08-16 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_post_destacado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='destacado',
        ),
    ]
