# Generated by Django 5.2.4 on 2025-08-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0009_categoria_imagen_alter_comentario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Una breve descripción de la categoría para SEO y para mostrar en el hub de categorías.', null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen representativa para la categoría', null=True, upload_to='imagenes_categorias/'),
        ),
    ]
