# Generated by Django 5.2.4 on 2025-08-21 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0010_alter_categoria_descripcion_alter_categoria_imagen'),
        ('noticias', '0010_notificacion'),
    ]

    operations = [
    ]
