# Generated by Django 5.2.4 on 2025-08-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0011_merge_20250821_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='imagenes_noticias/noticias_default.png', upload_to='imagenes_noticias'),
        ),
    ]
