# Generated by Django 5.2.4 on 2025-08-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0012_alter_post_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='editado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comentario',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comentario',
            name='fecha_edicion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
