# Generated by Django 5.2.4 on 2025-08-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0014_comentario_eliminado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, default='imagenes_categorias/categorias_default.png', help_text='Imagen representativa para la categoría', null=True, upload_to='imagenes_categorias/'),
        ),
    ]
